learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
""" Defines URL patterns for Learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topic page
    path('topics/', views.topics, name='topics'),
    # Single Topic Page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # New topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    # New entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
]

learning_logs/models.py
from django.db import models


# Create your models here.


class Topic(models.Model):
    """ A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text}"


class Entry(models.Model):
    """ Something specific learned about the topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """ Return a string representation of the model"""
        return f"{self.text[0:50]}..."

learning_logs/forms.py
from django import forms
from .models import Topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """ The home page for learning_logs. """
    return render(request, 'learning_logs/index.html')


def topics(request):
    """ Show all Topics. """
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """ Show a single topic and all its entries. """
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """ Add new topic. """
    if request.method != 'POST':
        # No data submitted; create blank form
        form = TopicForm()
    else:
        # POST data submitted.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    # Display blank or invalid forms.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """ Add new entry for topic. """
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted: create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

learning_logs/templates/learning_logs/base.html
<h3>
    <a href="{% url 'learning_logs:index' %}">Learning Logs</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</h3>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning logs helps you keep track of your learning, for any topic you are interested in learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h4><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4>

  <p><strong>Add new entry:</strong></p>
  <form action="{% url 'learning_logs:new_entry', topic.id %}" method='post'>
    {% csrf_token %}
    {{ form }}
    <button name='submit'>Add entry</button>
  </form>

{% endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h4>Add a new topic: </h4>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <h4>Topic: {{topic}}</h4>

  <p><strong>Entries: </strong></p>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.date_added|date:'M d, Y h:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
      </li>
    {% empty %}
      <li>There are no entries for this topic yet...</li>
    {% endfor %}
  </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <h4>Topics</h4>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet...</li>
    {% endfor %}
  </ul>
  <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>
{% endblock content %}